### PR TITLE
Split exec, and start

### PR DESCRIPTION
**Pull request by voidfiles**
Regading issue #118 what if you split the scripts up againg.

Again, I really don't know much about what you are trying to do here, I just know that I am dealing with this as a user. This seems like it would fix the issue. I totally understand if there are larger concerns that I am unware of.

### CODE REVIEW

**Comment by progrium** [comment]
So we all agree an issue should be opened with dokku-shoreman? Herokuish branch is designed the same way, so it'll have the same issue. I don't think an upstream component should accommodate a downstream component that is hacking around with the upstream component...

**Comment by darkpixel** [comment]
Issue already open here: https://github.com/statianzo/dokku-shoreman/issues/11

**Comment by voidfiles** [comment]
+1

**Comment by yabawock** [comment]
Guess we can close this one as it has been reported to the author of the plugin.

**Pull request closed without merging**
