### PR TITLE
drops all buildstep scripts and defers operations to herokuish tool

### PR DESCRIPTION
**Pull request by progrium**
- dropped all scripts under builder (replaced by [herokuish](https://github.com/gliderlabs/herokuish))
- any extra files are installed via rootfs
- backwards compatibilty is maintained via symlinks+wrappers
- deprecated ./buildstep script

### CODE REVIEW

**Comment by progrium** [comment]
One idea, what do you think:

Perhaps if `procfile exec` doesn't create a random user if it sees what it's running is already a non-nobody user, and instead runs is its owner. Then there can be an option to chown /app to a random user immediately after the build before it's committed to a layer.

**Comment by yabawock** [comment]
@progrium I take it that `non-nobody` user was meant to be `non-root`. 

I think that would result in a few places that need to take into consideration if they are being run as root or non-root. One such example is running commands as `non-root`. `setuidgid` can not be invoked then as it would fail dropping privileges. And seeing that herokuish is meant to be used as `/start` and `/exec` that would only leave docker to supply a non-privileged user context as there is nothing else in the chain of commands that could drop permissions. That would mean adjustment for all consumers of herokuish.

I think something along these lines would be a better workaround for the time being:
1) create the randomized user happens the build stage. The permission problems on AUFS would go away as it all happens in on layer. The user wouldn't be randomized quite as often as it only happens during builds and not on each start but I think that is an acceptable compromise. 

2) Instead of `procfile-randomize-user()` there would be a function to determine the user from the buildstep, for example by using something along the lines of `local username=$(stat --format="%U" ${app_path})`. This user would be used in all subsequent steps just as the information from `procfile-randomize-user()` is being used now. 

This should be a minor adjustment that can easily be reverted for a more frequent user randomization once the bugs with AUFS have been ironed out.

**Comment by progrium** [comment]
This is about what I was going to commit. Except you can force the user in either case by having `USER` set.

 * when you build: user will be random unless `USER` is set. 
 * when you run/exec: user will be owner of `$app_path` unless `USER` is set.

The only case this doesn't allow is random user on each run/exec.

**Comment by progrium** [comment]
It makes the behavior more complicated, but perhaps if the owner of `$app_path` is nobody it runs as random user. You can enforce running as nobody by setting `USER`.

**Comment by progrium** [comment]
Or maybe it would be better to randomize on run if `USER=random`? Seems more explicit, but sort of overloading semantics of that variable...

**Comment by yabawock** [comment]
Taking into account that having a random user on each run is mostly limited due to the AUFS bugs I would stick to the simple case of randomizing the account on build and USER forcing the account name. Everything else seems asking for trouble down the line. I would consider switching from random user on build to random user on run once the AUFS issues have been resolved. That change should be backward compatible and could be implemented with a new major version of herokuish.

If you want to make full randomization available now I would prefer a second variable, something like RANDOMIZE. If this var is empty or "build" randomize on build, if it's "exec" randomize on each invocation. USER would the override RANDOMIZE.

**Comment by michaelshobbs** [comment]
My apologies if this has been asked but why would you want to randomize on run? I assume this to be able to use the same buildstep image across multiple containers with different users but what about containers that share volumes. Wouldn't you run into file permission issues?

As long as randomization is overridable via variable or some other way, I think I'm +1.

**Comment by progrium** [comment]
Yeah I think I'll stick to the simple model of random on build with `USER` override.

**Comment by progrium** [comment]
Whoa! All the tests pass with the new release of Herokuish. Alright, what do you guys think?

**Comment by josegonzalez** [comment]
PR doesn't merge cleanly, mind rebasing? I'll pull this down on my dev box and test it out against a few apps (though I defer to @michaelshobbs since he uses dokku in production and therefore this)

**Comment by josegonzalez** [comment]
@progrium My current other concern is that buildstep get tested against herokuish master (so that we can see breaking changes as they happen). I am not familiar with wrecker as much as I am travisci, but would it be possible to add a "allow_failures" build that refs herokuish master? That would be very useful going forward, though obviously not required to merge this :)

**Comment by michaelshobbs** [comment]
Running tests against `herokuish` image now.

**Comment by michaelshobbs** [comment]
All tests, except static web site deployment, pass.

**Comment by michaelshobbs** [comment]
The static buildpack drops a `.release` file instead of using a `Procfile`

```
root@b1eee843db1d:/# cat /app/.release
---

addons:
config_vars:
  PATH: /usr/local/bin:/usr/bin:/bin:/app/nginx
default_process_types:
  web: /app/start_nginx
```

Seems as though `/bin/herokuish` doesn't handle that?

**Comment by progrium** [comment]
Do you have a link to output? What is the failure? Or what is the missing behavior specifically?

**Comment by michaelshobbs** [comment]
I have this:

```
root@dokku:~/dokku# docker ps -a
c824430ce56c        dokku/test-static-herokuish:latest   "/start web"           7 hours ago         Exited (126) 7 hours ago                       adoring_banach
root@dokku:~/dokku# docker logs adoring_banach
/app/start_nginx: line 4: exec: nginx: cannot execute: Is a directory
```

**Comment by yabawock** [comment]
My ruby, node, PHP and static (using the PHP buildpack) apps all work fine when built with herokuish. 

@progrium I think herokuish is not honoring the ENV keys set in .release. Because of that the path isn't right and exec only sees the `nginx` directory instead of the executable in that directory.

**Comment by yabawock** [comment]
> Do you have a link to output? What is the failure? Or what is the missing behavior specifically?

I've played around with this branch a bit more and can confirm it's due to the `config_vars` from the `.release` file not being parsed. I haven't verified if Heroku is still silently honoring the key in the `.release` file, officially this key has been deprecated a long time ago and isn't even mentioned in the (documentation)[https://devcenter.heroku.com/articles/buildpack-api#bin-release] anymore. Maybe switching to `herokuish` is the right time to drop support for that in `buildstep` as well?

@michaelshobbs Which buildpack are you using for the static pages, I think it would be a very simple fix to make it adhere to current standards and would be willing to create a PR with the fix.

**Comment by progrium** [comment]
Since `.release` is just something I think I came up with for Dokku/buildstep a long time and not a real Heroku thing, maybe we try to drop it? @michaelshobbs @josegonzalez what do you guys think? Do we need it?

**Comment by josegonzalez** [comment]
We should provide an alternative for people trying to deploy static sites - even if its through documentation. Is there a static site buildpack out there we can switch to?

**Comment by progrium** [comment]
We can also fix the existing one to not use .release? Or as Morton said, I
think you can just use the PHP buildpack...

On Wed, Feb 18, 2015 at 2:51 PM, Jose Diaz-Gonzalez <
notifications@github.com> wrote:

> We should provide an alternative for people trying to deploy static sites
> - even if its through documentation. Is there a static site buildpack out
> there we can switch to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/buildstep/pull/129#issuecomment-74945262>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by yabawock** [comment]
@progrium `.release` is a real Heroku thing, you shouldn't drop it completely as it contains the default process types when no `Procfile` exists.

@josegonzalez I already offered to fix the current one, just need to know which of the many it is. Or just use the official PHP Buildpack. Providing an empty `composer.json` in the root of your repository.

*composer.json:*
```javascript
{}
```

Results in the following deploy:
```
-----> PHP app detected
-----> No runtime requirements in composer.json, defaulting to PHP 5.6.1.
-----> Installing system packages...
       - PHP 5.6.1
       - Apache 2.4.10
       - Nginx 1.6.0
-----> Installing PHP extensions...
       - zend-opcache (automatic; bundled, using 'ext-zend-opcache.ini')
-----> Installing dependencies...
       Composer version 1.0-dev (833ce984264204e7d6576ab082660105c7d8f04c) 2015-02-17 21:55:44
       Loading composer repositories with package information
       Installing dependencies
       Nothing to install or update
       Generating optimized autoload files
-----> Preparing runtime environment...
-----> Discovering process types
       Procfile declares types -> web
       Default process types for PHP -> web
```

Nice and easy static website with all the customizing options the Heroku buildpack provides (like selecting the preferred type of webserver or the document root).

**Comment by josegonzalez** [comment]
The one in use in [our tests](https://github.com/progrium/dokku/blob/master/tests/apps/static/.env) is [here](https://github.com/florianheinemann/buildpack-nginx)

**Comment by yabawock** [comment]
PR with the fix is submitted: florianheinemann/buildpack-nginx#3

Feel free to try using the following buildpack url: `https://github.com/yabawock/buildpack-nginx.git`

**Comment by josegonzalez** [comment]
We should probably push all those changes upstream to progrium's original repo at some point :P

**Comment by progrium** [comment]
@yabawock are you sure about `.release`? I don't see it mentioned anywhere in Heroku Buildpack API docs. They do use the output of `bin/release`, yes, but they don't actually make a `.release` file. I'm saying we can probably put the output of it elsewhere ... for example, default proc types are just written to a Procfile. `config_vars` can be added to `profile.d`

**Comment by josegonzalez** [comment]
@yabawock's buildpack [seems to work](https://github.com/progrium/dokku/pull/986) with dokku master, though I'm with @progrium on the info being put in the `Procfile` and `profile.d` directory.

**Comment by yabawock** [comment]
@progrium You're right. Storing the info from `bin/release` in a `.release` file is something that only buildstep does, Heroku seems to only parse the output.

Regarding the `config_vars` - Heroku seems to be using it in quite a few of the official buildpacks without documenting it anymore. At the moment it might be wise to still have support for it in herokuish

**Comment by progrium** [comment]
So I'm going to suggest we make sure bin/release output is used but not
write a .release file. Once that's done in Herokuish I think we'll be ready
to merge.

On Thu, Feb 19, 2015 at 5:19 AM, Morton Jonuschat <notifications@github.com>
wrote:

> @progrium <https://github.com/progrium> You're right. Storing the info
> from bin/release in a .release file is something that only buildstep
> does, Heroku seems to only parse the output.
>
> Regarding the config_vars - Heroku seems to be using it in quite a few of
> the official buildpacks without documenting it anymore. At the moment it
> might be wise to still have support for it in herokuish
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/buildstep/pull/129#issuecomment-75035749>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
Sorry I didn't get back to this. Been sick for a few days. Just now vertical again. The buildpack fork works great against `herokuish` and I believe @josegonzalez has already checked it into the test suite for dokku.

**Comment by progrium** [comment]
I can't stand this branch and keeping it in sync with master. I'm just going to merge it to master and deal with the bin/release output before next buildstep release. It's an issue in herokuish anyway, no changes would be needed here.

**Comment by josegonzalez** [comment]
+1 ship it :shipit:

**Comment by progrium** [comment]
I guess it did not detect this in master because of rebase/merging wonkiness.

**Pull request closed without merging**
