### PR TITLE
Update herokuish to 0.3.1 release

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by michaelshobbs** [comment]
:+1:

**Comment by michaelshobbs** [comment]
merge-y, merge?

**Comment by michaelshobbs** [comment]
new release-y release? :smile:

**Comment by josegonzalez** [comment]
[You're so needy!](https://github.com/progrium/buildstep/releases/tag/2015-07-14)

**Comment by michaelshobbs** [comment]
@josegonzalez i think there's some magic to upload the buildstep image to github as well?

example: https://github.com/progrium/buildstep/releases/tag/2014-12-16

**Comment by michaelshobbs** [comment]
Once the new one is up, we can update dokku's Makefile: https://github.com/progrium/dokku/blob/97eefef04a3bc918804dff4a6d1edcf32f069f4b/Makefile#L6

Then our scala test will pass.

**Pull request merged**
